<?php
/**
 * Edit account form template
 *
 * @var $block \Magento\Customer\Block\Form\Edit
 */
?>
<form class="form form-edit-account"  method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
   <fieldset class="fieldset info">
        <fieldset class="fieldset">
			   <legend class="legend"><span><?php echo __('Event Information') ?></span></legend><br>
				<div class="field required">
					<label for="email_address" class="label"><span><?php echo __('Event Name') ?></span></label>
					<div class="control">
						<input type="text" name="eventname" id="eventname" class="eventname" value="" title="<?php echo __('Event Name') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
					</div>
				</div>
	<div class="field required">
	<label for="email_address" class="label"><span><?php echo __('Event Date') ?></span></label>
    <div class="control">
			<input type="text" 
           class="input-text required-entry" 
           id="calendar_inputField" 
           name="dob"
           aria-required="true" />	
	</div>
	</div>
	<div class="field required">
	<label for="notificationdate" class="label"><span><?php echo __('Notification Date') ?></span></label>
    <div class="control">
			<input type="text" 
           class="input-text required-entry" 
           id="notificationdate" 
           name="notificationdate"
           aria-required="true" />	
	</div>
	</div>
	<div class="field required">
	<label for="friendemail" class="label"><span><?php echo __('Friend Email') ?></span></label>
    <div class="control">
			<input type="email" 
           class="input-text required-entry" 
           id="friendemail" 
           name="friendemail"
           aria-required="true" />	
	</div>
	</div>
	<div class="field required">
	<label for="eventmessage" class="label"><span><?php echo __('Message') ?></span></label>
    <div class="control">
			<input type="text" 
           class="input-text required-entry" 
           id="eventmessage" 
           name="eventmessage"
           aria-required="true" />	
	</div>
	</div>
    <script>
        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
            $("#calendar_inputField").calendar({
                changeYear: true,
                changeMonth: true,
				dateFormat: "yy-mm-dd", 
                yearRange: "1920:+2",
                buttonText: "Select Date",
            });
			$("#notificationdate").calendar({
                changeYear: true,
                changeMonth: true,
				dateFormat: "yy-mm-dd", 
                yearRange: "1920:+2",
                buttonText: "Select Date",
            });
        });
    </script>

		   </fieldset>
		   <div class="actions-toolbar">
				<div class="primary">
					<button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
				</div>
			</div>
	</fieldset>
</form>

<script>
    require(['jquery'],function(){
    jQuery(document).ready(function() {
        jQuery("#form-validate").submit(function(){

            var url = "<?php echo $block->getBaseUrl().'customer/account/addevent/' ?>";
			//alert(dataString);
            jQuery.ajax({
            url: url,
            type: "POST",
            data: jQuery('#form-validate').serialize(),
            showLoader: true,
			cache: false,
            success: function(response){
                console.log(response);
            }
        });
        return false;
        });
    });
});
</script>
